### ISSUE TITLE
Use 'actual' and 'expected' properties when instantiating AssertionFailedError

### ISSUE THREAD

**Issue by jlink** [junit-team/junit-framework#138]
Use `new AssertionFailedError(message, expected, actual)` in the following cases:
- [X] Change `expected` and `actual` instance variables and parameters to only store `Serializable` values.
- [x] `Assertions.assertEquals`
- [x] ~~`Assertions.assertNotEquals`~~ (see #282)
- [x] `Assertions.assertSame`
- [x] ~~`Assertions.assertNotSame`~~ (see #282)
- [x] `Assertions.assertNull`
- [x] ~~`Assertions.assertNotNull`~~ (see #282)

**Comment by sbrannen** [comment]
Since the API for `AssertionFailedError` in the OTA is currently unstable (i.e., slated to be changed), we should hold off on changing JUnit 5's `Assertions` to depend on this feature.

**Comment by jlink** [comment]
What about the IDEs that would like to provide a comparison view?

**Comment by bechte** [comment]
Wouldn't they be able to extract that information the same way they do it today?

**Comment by jlink** [comment]
Nowadays they use a JUnit 4 exception:
http://junit.sourceforge.net/javadoc/org/junit/ComparisonFailure.html

2016-01-28 18:45 GMT+01:00 Stefan Bechtold <notifications@github.com>:

**Comment by bechte** [comment]
This exception is thrown by JUnit only. The IDEs support comparison views also for `AssertionError`s that are raised by libraries like Hamcrest or AssertJ. As far as I know, none of them are using  `ComparisonFailure`. Therefore, I think it would be fine to use an `AssertionFailedError` that provides a message with a formatting closed to what Hamcrest or AssertJ produces. This would probably be handled by the IDEs wisely and we would not depend on an unstable API.

**Comment by jlink** [comment]
Since @akozlova wanted to use expected/actual in IntelliJ support, I suggest we should implemented.
Since we do already rely on `AssertionFailedError` from opentest4j, actually using the fields does not change the dependency strength much.

I additionally suggest to stringify expected and actual values if they are not serializable.

**Comment by marcphilipp** [comment]
I'm starting to work on this issue.

**Comment by marcphilipp** [comment]
I've addressed the first subtask in opentest4j, see ota4j-team/opentest4j@dada365668cd918d0273f22bbfdcdadd8eac5643 for details. Since I won't have time to work on this issue in the next few days, I'll remove the *in progress* tag.

**Comment by marcphilipp** [comment]
The remaining subtask should be pretty straight-forward. Therefore, I'm adding the *up-for-grabs* label.

**Comment by marcphilipp** [comment]
I'm picking up work on this issue again.

**Comment by marcphilipp** [comment]
`assertEquals`, `assertSame`, and `assertNull` now pass actual and expected values to the constructor of `AssertionFailedError.

I don't think it makes sense to fill `expected` and `actual` for `assertNotNull`, `assertNotSame`, and `assertNotEquals` because there's no expected value in these cases. We could change `AssertionFailedError` to allow only specifying an actual value.

@junit-team/junit-lambda What do you think?

**Comment by marcphilipp** [comment]
I'm closing this issue. `assertNotNull`, `assertNotSame`, and `assertNotEquals` will be addressed in #282.
